[game]
soft_max_players = 20
lobbyduration = 180
lobbyenabled = true
hostname = "Aurum Sector"
role_timers = true
dynamic_roles.enabled = false

[chat]
motd = "wawa"

[console]
login_host_user = "AverageDiggy"



[admin]
new_player_join_sound = true
deadmin_on_join = true
new_player_threshold = 600
alert.min_players_sharing_connection = 2
server_ban_erase_player = true
see_own_notes = true
show_pii_onban = true
admins_count_in_playercount = true
chat_discord_channel_id = 1484273228217188585
ahelp_discord_channel_id = 1484285606396825680
dead_chat_discord_channel_id = 1484273127126077532

[ahelp]
admin_prefix = true
admin_prefix_webhook = true

[biomass]
easy_mode = false

[ooc]
show_ooc_patron_color = false
discord_channel_id = 1484273168532111451

[shuttle]
auto_call_time = 360
mass_limit = 0

[surgery]
can_operate_on_self = true

[nf14.salvage]
expedition_rewards_enabled = true

[nf14.respawn]
time = 600

[auth]
mode = 1

[net]
tickrate = 30
max_connections = 2000
lidgren_log_warning = false
lidgren_log_error = false
log_late_msg = false

[log]
path = "logs"
format = "log_%(date)s-%(time)s.txt"
level = 2
enabled = 0
